- name: Install dependencies
  run: pip install -r requirements.txt
    name: Python tests
    on: [push]
    jobs:
      tests:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4
          - name: Set up Python 3.10
            uses: actions/setup-python@v5
            with:
              python-version: '3.10'
          - name: Install deps
            run: |
              python -m pip install --upgrade pip
              if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          - name: Run pytest
            run: pytest
